version: '3.8'
services:
  frontend:
    build:
      context: ./se-project-17_soft-serve
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=SoftServe_get_A_SoftEng
      - MONGO_URI=mongodb+srv://6733270421:ZMwKDw9RUd8HgGu0@swproject.wzbwwkg.mongodb.net/?retryWrites=true&w=majority&appName=SWProject
      - FRONTEND_URL=http://localhost:3000
      - BACKEND_URL=http://backend:5000/
    depends_on:
      - backend
    networks:
      - backend-network  

  backend:
    build:
      context: ./se-project-backend-17_soft-serve
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://6733270421:ZMwKDw9RUd8HgGu0@swproject.wzbwwkg.mongodb.net/?retryWrites=true&w=majority&appName=SWProject
      - JWT_SECRET=SoftServe_get_A_SoftEng
      - PORT=5000
      - NODE_ENV=development
      - JWT_EXPIRE=30d
      - JWT_COOKIE_EXPIRE=30
      - HOST=http://localhost
    volumes:
      - ./se-project-backend-17_soft-serve:/usr/src/app
      - /usr/src/app/node_modules 
    networks:
      - backend-network  

networks:
  backend-network:
    driver: bridge